require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'


namespace :autoclass do

  desc "Run unsupervised on full data set to observe class counts."
  task :class_count do
    ( 36..100 ).to_a.each do |j|
      gsub_file( './lrs.s-params', /fixed_j = (\d+)/, "fixed_j = #{ j }" )
      `./autoclass -search lrs.db2 lrs.hd2 lrs.model lrs.s-params`
      `./asave class_count_j_#{ j }`
    end
  end

  desc "Run unsupervised on full data set for many fixed_j"
  task :unsupervised do
    ( 2..50 ).to_a.each do |j|
      gsub_file( './lrs.s-params', /fixed_j = (\d+)/, "fixed_j = #{ j }" )
      `./autoclass -search lrs.db2 lrs.hd2 lrs.model lrs.s-params`
      puts "n"
      `./autoclass -reports lrs.results-bin lrs.search lrs.r-params`
      `./asave short_#{ j }`
    end
  end

  desc "Run unsupervised on 90/10 training/testing split"
  task :ninety_ten do
    5.times do |i|
      lines = File.readlines( './lrs.db2' )
      testing = []
      ( lines.length * 0.1 ).to_i.times do
        testing << lines.delete_at( rand( lines.length ) )
      end
      File.open( './lrs.training.db2', 'w' ) do |f|
        f.write lines.join( '\n' )
      end
      File.open( './lrs.testing.db2', 'w' ) do |f|
        f.write testing.join( '\n' )
      end

      `./autoclass -search lrs.training.db2 lrs.hd2 lrs.model lrs.s-params`
      `./autoclass -reports lrs.results-bin lrs.search lrs.r-params`
      `./autoclass -predict lrs.testing.db2 lrs.results-bin lrs.search lrs.r-params`
      `./asave split_90_10_run_#{ i }`
    end
  end

  desc "Run unsupervised on 80/20 training/testing split"
  task :eighty_twenty do
    5.times do |i|
      lines = File.readlines( './lrs.db2' )
      testing = []
      ( lines.length * 0.2 ).to_i.times do
        testing << lines.delete_at( rand( lines.length ) )
      end
      File.open( './lrs.training.db2', 'w' ) do |f|
        f.write lines.join( '\n' )
      end
      File.open( './lrs.testing.db2', 'w' ) do |f|
        f.write testing.join( '\n' )
      end

      `./autoclass -search lrs.training.db2 lrs.hd2 lrs.model lrs.s-params`
      `./autoclass -reports lrs.results-bin lrs.search lrs.r-params`
      `./autoclass -predict lrs.testing.db2 lrs.results-bin lrs.search lrs.r-params`
      `./asave split_80_20_run_#{ i }`
    end
  end

  desc "Run unsupervised on 70/30 training/testing split"
  task :seventy_thirty do
    5.times do |i|
      lines = File.readlines( './lrs.db2' )
      testing = []
      ( lines.length * 0.3 ).to_i.times do
        testing << lines.delete_at( rand( lines.length ) )
      end
      File.open( './lrs.training.db2', 'w' ) do |f|
        f.write lines.join( '\n' )
      end
      File.open( './lrs.testing.db2', 'w' ) do |f|
        f.write testing.join( '\n' )
      end

      `./autoclass -search lrs.training.db2 lrs.hd2 lrs.model lrs.s-params`
      `./autoclass -reports lrs.results-bin lrs.search lrs.r-params`
      `./autoclass -predict lrs.testing.db2 lrs.results-bin lrs.search lrs.r-params`
      `./asave split_70_30_run_#{ i }`
    end
  end

  desc "Run unsupervised on 60/40 training/testing split"
  task :sixty_forty do
    5.times do |i|
      lines = File.readlines( './lrs.db2' )
      testing = []
      ( lines.length * 0.4 ).to_i.times do
        testing << lines.delete_at( rand( lines.length ) )
      end
      File.open( './lrs.training.db2', 'w' ) do |f|
        f.write lines.join( '\n' )
      end
      File.open( './lrs.testing.db2', 'w' ) do |f|
        f.write testing.join( '\n' )
      end

      `./autoclass -search lrs.training.db2 lrs.hd2 lrs.model lrs.s-params`
      `./autoclass -reports lrs.results-bin lrs.search lrs.r-params`
      `./autoclass -predict lrs.testing.db2 lrs.results-bin lrs.search lrs.r-params`
      `./asave split_60_40_run_#{ i }`
    end
  end

  desc "Run unsupervised on 50/50 training/testing split"
  task :fifty_fifty do
    5.times do |i|
      lines = File.readlines( './lrs.db2' )
      testing = []
      ( lines.length * 0.5 ).to_i.times do
        testing << lines.delete_at( rand( lines.length ) )
      end
      File.open( './lrs.training.db2', 'w' ) do |f|
        f.write lines.join( '\n' )
      end
      File.open( './lrs.testing.db2', 'w' ) do |f|
        f.write testing.join( '\n' )
      end

      `./autoclass -search lrs.training.db2 lrs.hd2 lrs.model lrs.s-params`
      `./autoclass -reports lrs.results-bin lrs.search lrs.r-params`
      `./autoclass -predict lrs.testing.db2 lrs.results-bin lrs.search lrs.r-params`
      `./asave split_50_50_run_#{ i }`
    end
  end

  desc "Run unsupervised on 40/60 training/testing split"
  task :forty_sixty do
    5.times do |i|
      lines = File.readlines( './lrs.db2' )
      testing = []
      ( lines.length * 0.6 ).to_i.times do
        testing << lines.delete_at( rand( lines.length ) )
      end
      File.open( './lrs.training.db2', 'w' ) do |f|
        f.write lines.join( '\n' )
      end
      File.open( './lrs.testing.db2', 'w' ) do |f|
        f.write testing.join( '\n' )
      end

      `./autoclass -search lrs.training.db2 lrs.hd2 lrs.model lrs.s-params`
      `./autoclass -reports lrs.results-bin lrs.search lrs.r-params`
      `./autoclass -predict lrs.testing.db2 lrs.results-bin lrs.search lrs.r-params`
      `./asave split_40_60_run_#{ i }`
    end
  end

  desc "Run unsupervised on 30/70 training/testing split"
  task :thirty_seventy do
    5.times do |i|
      lines = File.readlines( './lrs.db2' )
      testing = []
      ( lines.length * 0.7 ).to_i.times do
        testing << lines.delete_at( rand( lines.length ) )
      end
      File.open( './lrs.training.db2', 'w' ) do |f|
        f.write lines.join( '\n' )
      end
      File.open( './lrs.testing.db2', 'w' ) do |f|
        f.write testing.join( '\n' )
      end

      `./autoclass -search lrs.training.db2 lrs.hd2 lrs.model lrs.s-params`
      `./autoclass -reports lrs.results-bin lrs.search lrs.r-params`
      `./autoclass -predict lrs.testing.db2 lrs.results-bin lrs.search lrs.r-params`
      `./asave split_30_70_run_#{ i }`
    end
  end

  desc "Run unsupervised on 20/80 training/testing split"
  task :twenty_eighty do
    5.times do |i|
      lines = File.readlines( './lrs.db2' )
      testing = []
      ( lines.length * 0.8 ).to_i.times do
        testing << lines.delete_at( rand( lines.length ) )
      end
      File.open( './lrs.training.db2', 'w' ) do |f|
        f.write lines.join( '\n' )
      end
      File.open( './lrs.testing.db2', 'w' ) do |f|
        f.write testing.join( '\n' )
      end

      `./autoclass -search lrs.training.db2 lrs.hd2 lrs.model lrs.s-params`
      `./autoclass -reports lrs.results-bin lrs.search lrs.r-params`
      `./autoclass -predict lrs.testing.db2 lrs.results-bin lrs.search lrs.r-params`
      `./asave split_20_80_run_#{ i }`
    end
  end

  desc "Run unsupervised on 10/90 training/testing split"
  task :ten_ninety do
    5.times do |i|
      lines = File.readlines( './lrs.db2' )
      testing = []
      ( lines.length * 0.9 ).to_i.times do
        testing << lines.delete_at( rand( lines.length ) )
      end
      File.open( './lrs.training.db2', 'w' ) do |f|
        f.write lines.join( '\n' )
      end
      File.open( './lrs.testing.db2', 'w' ) do |f|
        f.write testing.join( '\n' )
      end

      `./autoclass -search lrs.training.db2 lrs.hd2 lrs.model lrs.s-params`
      `./autoclass -reports lrs.results-bin lrs.search lrs.r-params`
      `./autoclass -predict lrs.testing.db2 lrs.results-bin lrs.search lrs.r-params`
      `./asave split_10_90_run_#{ i }`
    end
  end

end

def gsub_file( relative_destination, regexp, *args, &block )
  path = relative_destination
  content = File.read( path ).gsub( regexp, *args, &block )
  File.open( path, 'wb' ) { |file| file.write( content ) }
end
