# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'


namespace :autoclass do

  desc "Run unsupervised on full data set for many fixed_j"
  task :unsupervised do
    ( 2..50 ).to_a.each do |j|
      gsub_file( './lrs.s-params', /fixed_j = (\d+)/, "fixed_j = #{ j }" )
      `./autoclass -search lrs.db2 lrs.hd2 lrs.model lrs.s-params`
      puts "n"
      `./autoclass -reports lrs.results-bin lrs.search lrs.r-params`
      `./asave short_#{ j }`
    end
  end

end

def gsub_file( relative_destination, regexp, *args, &block )
  path = relative_destination
  content = File.read( path ).gsub( regexp, *args, &block )
  File.open( path, 'wb' ) { |file| file.write( content ) }
end
